// gen-ts — 从 idl/*.thrift 生成纯 TypeScript 类型声明(.d.ts)到 gen/ts/。
//
// 与 cmd/gen-openapi 同源同真相:同一批 service IDL、同一套字段序列化名规则
// (serializedFieldName:优先 api.* 注解值,回退字段名),保证 gen/(Go 模型)、
// openapi/openapi.json、gen/ts/(前端类型)三份产物对同一 IDL 恒一致;
// main_test.go 另以 openapi.json 的 schema 名单做跨产物对账,防两套字段名规则漂移。
//
// 产出(全部随仓提交,勿手改;CI --check 守卫):
//
//	gen/ts/<domain>.d.ts  每 go namespace 一个模块,纯 interface/type,零 runtime
//	gen/ts/index.d.ts     桶出口:export type * as <domain> from './<domain>'
//
// 跨域同名类型(现网 BaseConfig/StorageConfig/EmptyReq)由命名空间隔离,
// 故 index 不做顶层 export *;消费方
// `import type { share } from '@filescodebox/contracts'` 后按 share.ShareDetail 取用。
//
// 类型映射:i*/double → number(JSON 反序列化本就是 number,现网值域(时间戳/
// 字节数)远低于 2^53;未来出现大整数场景在消费侧转 bigint/string,勿在此全局改动);
// string/binary → string;list/set → T[];map → Record<string, V>(JSON object
// 键恒为字符串);struct/union/exception → interface;enum → 数字字面量联合;
// optional → ?:;typedef → type 别名。
//
// 用法:
//
//	go run ./cmd/gen-ts            # 生成 gen/ts/
//	go run ./cmd/gen-ts --check    # 只校验 gen/ts 与 IDL 同步(CI 用)
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/cloudwego/thriftgo/parser"
)

const (
	idlDir    = "idl"
	outputDir = "gen/ts"
	genNote   = "Code generated by contracts cmd/gen-ts from idl/*.thrift. DO NOT EDIT."
)

func main() {
	check := flag.Bool("check", false, "校验 gen/ts 与 IDL 是否同步，不写出")
	flag.Parse()

	files, err := Generate(idlDir)
	if err != nil {
		fatal("%v", err)
	}

	if *check {
		if err := checkSync(files); err != nil {
			fatal("%v", err)
		}
		fmt.Printf("✓ %s 与 idl/ 定义同步（%d 文件）\n", outputDir, len(files))
		return
	}

	if err := writeAll(files); err != nil {
		fatal("%v", err)
	}
	fmt.Printf("✓ 已生成 %s（%d 域模块 + index.d.ts）\n", outputDir, len(files)-1)
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "[gen-ts] ERROR: "+format+"\n", args...)
	os.Exit(1)
}

// ---------------------------------------------------------------- 生成核心

// typeDef 作用域条目：名字 → 定义处（域 + struct/enum 定义指针 / typedef 别名）
type typeDef struct {
	domain string
	// st struct 定义指针（enum/typedef 无此字段）
	st *parser.StructLike
	// aliasType typedef 指向的原类型（仅 typedef 条目非 nil）
	aliasType *parser.Type
}

// domainFile 单域类型模块的累积器（同域被多个 IDL 贡献时合并、同名声明报错）
type domainFile struct {
	sources []string          // 贡献本域的 IDL 文件（仅头注释用）
	decls   map[string]string // 类型名 → 声明块（查重）
	order   []string          // 声明顺序（源码序，保证产物确定性）
	imports map[string]bool   // 跨域引用的域 → 需要 import './domain'
}

func newDomainFile() *domainFile {
	return &domainFile{decls: map[string]string{}, imports: map[string]bool{}}
}

func (d *domainFile) add(name, decl string) error {
	if _, dup := d.decls[name]; dup {
		return fmt.Errorf("域内类型重名: %s", name)
	}
	d.decls[name] = decl
	d.order = append(d.order, name)
	return nil
}

// Generate 解析 dir 下全部带 service 的 IDL（含 include 闭包），产出
// 文件名（相对 outputDir）→ 内容。导出以便单测与跨产物对账直接消费。
func Generate(dir string) (map[string]string, error) {
	files, err := listServiceIDLs(dir)
	if err != nil {
		return nil, err
	}

	// 解析全部根文件并展开 include 闭包（与 gen-openapi 同口径）
	parsed := map[string]*parser.Thrift{} // filename → AST
	for _, f := range files {
		t, err := parser.ParseFile(f, []string{dir}, true)
		if err != nil {
			return nil, fmt.Errorf("解析 %s: %w", f, err)
		}
		collect(t, parsed)
	}

	names := make([]string, 0, len(parsed))
	for fn := range parsed {
		names = append(names, fn)
	}
	sort.Strings(names)
	ns := make(map[string]string, len(parsed)) // filename → go namespace 域名
	for _, fn := range names {
		ns[fn] = goNamespace(parsed[fn])
	}

	domains := map[string]*domainFile{}
	get := func(d string) *domainFile {
		df, ok := domains[d]
		if !ok {
			df = newDomainFile()
			domains[d] = df
		}
		return df
	}

	for _, fn := range names {
		t := parsed[fn]
		d := ns[fn]
		df := get(d)
		if !contains(df.sources, fn) {
			df.sources = append(df.sources, fn)
		}
		scope := localScopeOf(t, ns)
		for _, s := range t.Structs {
			if err := emitStruct(df, d, scope, s); err != nil {
				return nil, fmt.Errorf("%s: %w", fn, err)
			}
		}
		for _, s := range t.Unions {
			if err := emitStruct(df, d, scope, s); err != nil {
				return nil, fmt.Errorf("%s: %w", fn, err)
			}
		}
		for _, s := range t.Exceptions {
			if err := emitStruct(df, d, scope, s); err != nil {
				return nil, fmt.Errorf("%s: %w", fn, err)
			}
		}
		for _, e := range t.Enums {
			if err := emitEnum(df, e); err != nil {
				return nil, fmt.Errorf("%s: %w", fn, err)
			}
		}
	}
	if len(domains) == 0 {
		return nil, fmt.Errorf("%s 下未解析到任何类型（检查 IDL）", dir)
	}

	// 汇总为 <domain>.d.ts + index.d.ts（域排序，保证产物确定性）
	ds := make([]string, 0, len(domains))
	for d := range domains {
		ds = append(ds, d)
	}
	sort.Strings(ds)

	out := map[string]string{}
	var barrel strings.Builder
	fmt.Fprintf(&barrel, "// %s\n// 域命名空间桶出口（package.json \"types\" 指向本文件）。\n", genNote)
	barrel.WriteString("// 跨域同名类型由命名空间隔离，勿改为顶层 export *。\n\n")
	for _, d := range ds {
		df := domains[d]
		content, err := renderDomain(d, df)
		if err != nil {
			return nil, err
		}
		out[d+".d.ts"] = content
		fmt.Fprintf(&barrel, "export type * as %s from './%s';\n", d, d)
	}
	out["index.d.ts"] = barrel.String()
	return out, nil
}

// renderDomain 组装单域模块：头注释 + import 行 + 声明块（源码序）
func renderDomain(d string, df *domainFile) (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s\n// 域模块 %s（源: %s）——纯类型声明，零 runtime。\n",
		genNote, d, strings.Join(df.sources, ", "))

	if len(df.imports) > 0 {
		imps := make([]string, 0, len(df.imports))
		for im := range df.imports {
			imps = append(imps, im)
		}
		sort.Strings(imps)
		b.WriteString("\n")
		for _, im := range imps {
			fmt.Fprintf(&b, "import type { %s } from './%s';\n", im, im)
		}
	}

	for _, name := range df.order {
		b.WriteString("\n")
		b.WriteString(df.decls[name])
		b.WriteString("\n")
	}
	return b.String(), nil
}

// emitStruct struct/union/exception → interface（三者字段语义同构，与 openapi 同口径）
func emitStruct(df *domainFile, d string, scope map[string]typeDef, s *parser.StructLike) error {
	var b strings.Builder
	if c := jsdoc(s.ReservedComments); c != "" {
		b.WriteString(c)
		b.WriteString("\n")
	}
	if len(s.Fields) == 0 {
		fmt.Fprintf(&b, "export interface %s {}", s.Name)
		return df.add(s.Name, b.String())
	}
	fmt.Fprintf(&b, "export interface %s {\n", s.Name)
	for _, f := range s.Fields {
		tt := df.tsType(d, scope, f.Type)
		if c := jsdoc(f.ReservedComments); c != "" {
			fmt.Fprintf(&b, "  %s\n", c)
		}
		opt := f.Requiredness == parser.FieldType_Optional
		fmt.Fprintf(&b, "  %s%s %s;\n", serializedFieldName(f), ternary(opt, "?:", ":"), tt)
	}
	b.WriteString("}")
	return df.add(s.Name, b.String())
}

// emitEnum enum → 数字字面量联合类型（JSDoc 附成员名对照）
// 注:thriftgo 对未显式赋值的枚举项不回填序号,按 thrift 语义自上一项递增(首个为 0)
func emitEnum(df *domainFile, e *parser.Enum) error {
	var b strings.Builder
	if c := jsdoc(e.ReservedComments); c != "" {
		b.WriteString(c)
		b.WriteString("\n")
	}
	literals := make([]string, 0, len(e.Values))
	var members strings.Builder
	prev := int64(-1)
	for _, v := range e.Values {
		n := prev + 1
		if v.Value != 0 {
			n = v.Value
		}
		prev = n
		literals = append(literals, strconv.FormatInt(n, 10))
		if c := jsdoc(v.ReservedComments); c != "" {
			c = strings.TrimPrefix(c, "/**")
			c = strings.TrimSuffix(c, "*/")
			fmt.Fprintf(&members, "%s * %s = %d:%s\n", " ", v.Name, n, strings.TrimRight(c, " "))
		} else {
			fmt.Fprintf(&members, " * %s = %d\n", v.Name, n)
		}
	}
	b.WriteString("/** 成员对照:\n")
	b.WriteString(members.String())
	b.WriteString(" */\n")
	fmt.Fprintf(&b, "export type %s = %s;", e.Name, strings.Join(literals, " | "))
	return df.add(e.Name, b.String())
}

// tsType thrift 类型 → TS 类型表达式。跨域命名类型引用登记 import 并以
// `<domain>.<Name>` 限定;解析失败回退 unknown(编译可见,静默 any 不合规)。
func (df *domainFile) tsType(cur string, scope map[string]typeDef, t *parser.Type) string {
	if t == nil {
		return "unknown"
	}
	switch t.GetName() {
	case "bool":
		return "boolean"
	case "byte", "i8", "i16", "i32", "i64", "double":
		return "number"
	case "string", "binary":
		return "string"
	}
	name := t.GetName()
	// 容器判据用结构化字段(KeyType/ValueType):原始 AST 的 Category 未分类
	// (恒为 Constant),GetName 对容器也只返回裸名("list"/"map",无泛型后缀),
	// 名字形态匹配不可靠(修 gen-openapi 既有空 schema bug 的同一处教训)
	switch {
	case t.KeyType != nil: // map
		return fmt.Sprintf("Record<string, %s>", df.tsType(cur, scope, t.ValueType))
	case t.ValueType != nil: // list/set
		return df.tsType(cur, scope, t.ValueType) + "[]"
	}
	// typedef 别名:直接展开原类型(产物不引入中间名,消费面更小)
	if def, ok := resolveNamed(scope, t); ok && def.aliasType != nil {
		return df.tsType(cur, scope, def.aliasType)
	}
	if def, ok := resolveNamed(scope, t); ok {
		base := lastSegment(name)
		if def.domain != cur {
			df.imports[def.domain] = true
			return def.domain + "." + base
		}
		return base
	}
	return "unknown"
}

// resolveNamed 命名类型引用解析:本地名直查,include 引用按 "alias.Name" 查
func resolveNamed(scope map[string]typeDef, t *parser.Type) (typeDef, bool) {
	name := t.GetName()
	if t.Reference != nil && t.Reference.Name != "" {
		if d, ok := scope[t.Reference.Name]; ok {
			return d, true
		}
	}
	if d, ok := scope[name]; ok {
		return d, true
	}
	return typeDef{}, false
}

// ------------------------------------------------------------ IDL 收集/工具
// 以下与 cmd/gen-openapi 保持同构(过滤口径/namespace/include 作用域/字段
// 序列化名),任何一侧调整必须双侧同步并跑各自的 --check 与跨产物对账测试。

func listServiceIDLs(dir string) ([]string, error) {
	patterns := []string{filepath.Join(dir, "*.thrift"), filepath.Join(dir, "http", "*.thrift")}
	var out []string
	for _, p := range patterns {
		fs, err := filepath.Glob(p)
		if err != nil {
			return nil, err
		}
		out = append(out, fs...)
	}
	var withSvc []string
	for _, f := range out {
		b, err := os.ReadFile(f)
		if err != nil {
			return nil, err
		}
		if hasService(string(b)) {
			withSvc = append(withSvc, f)
		}
	}
	if len(withSvc) == 0 {
		return nil, fmt.Errorf("%s 下未找到带 service 定义的 IDL", dir)
	}
	sort.Strings(withSvc)
	return withSvc, nil
}

func hasService(src string) bool {
	for _, line := range strings.Split(src, "\n") {
		t := strings.TrimSpace(line)
		if strings.HasPrefix(t, "//") || strings.HasPrefix(t, "#") {
			continue
		}
		if strings.HasPrefix(t, "service ") || strings.HasPrefix(t, "service\t") {
			return true
		}
	}
	return false
}

func collect(t *parser.Thrift, into map[string]*parser.Thrift) {
	if t == nil {
		return
	}
	if _, ok := into[t.Filename]; ok {
		return
	}
	into[t.Filename] = t
	for _, inc := range t.Includes {
		collect(inc.Reference, into)
	}
}

func goNamespace(t *parser.Thrift) string {
	for _, ns := range t.Namespaces {
		if ns.Language == "go" && ns.Name != "" {
			if i := strings.LastIndex(ns.Name, "."); i >= 0 {
				return ns.Name[i+1:]
			}
			return ns.Name
		}
	}
	base := filepath.Base(t.Filename)
	return strings.TrimSuffix(base, filepath.Ext(base))
}

func localScopeOf(t *parser.Thrift, ns map[string]string) map[string]typeDef {
	m := map[string]typeDef{}
	p := ns[t.Filename]
	for _, s := range t.Structs {
		m[s.Name] = typeDef{domain: p, st: s}
	}
	for _, s := range t.Unions {
		m[s.Name] = typeDef{domain: p, st: s}
	}
	for _, s := range t.Exceptions {
		m[s.Name] = typeDef{domain: p, st: s}
	}
	for _, e := range t.Enums {
		m[e.Name] = typeDef{domain: p}
	}
	for _, td := range t.Typedefs {
		m[td.Alias] = typeDef{domain: p, aliasType: td.Type}
	}
	for _, inc := range t.Includes {
		if inc.Reference == nil {
			continue
		}
		ip := ns[inc.Reference.Filename]
		a := alias(inc.Path)
		for _, s := range inc.Reference.Structs {
			m[a+"."+s.Name] = typeDef{domain: ip, st: s}
		}
		for _, e := range inc.Reference.Enums {
			m[a+"."+e.Name] = typeDef{domain: ip}
		}
		for _, td := range inc.Reference.Typedefs {
			m[a+"."+td.Alias] = typeDef{domain: ip, aliasType: td.Type}
		}
	}
	return m
}

func alias(includePath string) string {
	base := filepath.Base(includePath)
	return strings.TrimSuffix(base, filepath.Ext(base))
}

func fieldAnnValue(f *parser.Field, key string) string {
	for _, ann := range f.Annotations {
		if strings.EqualFold(ann.Key, key) && len(ann.Values) > 0 {
			return ann.Values[0]
		}
	}
	return ""
}

// serializedFieldName 属性名:优先 api.* 注解值(与线上 JSON 序列化名一致),
// 无注解回退字段名
func serializedFieldName(f *parser.Field) string {
	for _, key := range []string{"api.body", "api.form", "api.query", "api.path"} {
		if v := fieldAnnValue(f, key); v != "" {
			return v
		}
	}
	return f.Name
}

func lastSegment(s string) string {
	if i := strings.LastIndex(s, "."); i >= 0 {
		return s[i+1:]
	}
	return s
}

func contains(s []string, v string) bool {
	for _, x := range s {
		if x == v {
			return true
		}
	}
	return false
}

func ternary(cond bool, a, b string) string {
	if cond {
		return a
	}
	return b
}

// jsdoc 保留注释 → JSDoc 块(清理注释前缀/行内 */ 防破坏结构);空注释返回空串
func jsdoc(comment string) string {
	var lines []string
	for _, l := range strings.Split(comment, "\n") {
		l = strings.TrimSpace(l)
		l = strings.TrimPrefix(l, "///")
		l = strings.TrimPrefix(l, "//")
		l = strings.TrimPrefix(l, "#")
		l = strings.TrimSpace(l)
		l = strings.ReplaceAll(l, "*/", "* /")
		if l != "" {
			lines = append(lines, l)
		}
	}
	if len(lines) == 0 {
		return ""
	}
	if len(lines) == 1 {
		return "/** " + lines[0] + " */"
	}
	var b strings.Builder
	b.WriteString("/**\n")
	for _, l := range lines {
		b.WriteString(" * " + l + "\n")
	}
	b.WriteString(" */")
	return b.String()
}

// ---------------------------------------------------------------- 产物落盘

// checkSync 内存产物与仓内 gen/ts 逐字节对账,并检测残留文件
func checkSync(files map[string]string) error {
	committed := map[string]bool{}
	entries, err := os.ReadDir(outputDir)
	if err != nil {
		return fmt.Errorf("读取 %s: %w（先运行 go run ./cmd/gen-ts 生成）", outputDir, err)
	}
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".d.ts") {
			committed[e.Name()] = true
		}
	}
	for rel, content := range files {
		b, err := os.ReadFile(filepath.Join(outputDir, rel))
		if err != nil {
			return fmt.Errorf("%s 缺失: 先运行 `go run ./cmd/gen-ts` 更新后提交", rel)
		}
		if string(b) != content {
			return fmt.Errorf("%s 与 idl/ 不同步,请运行 `go run ./cmd/gen-ts` 更新后提交", rel)
		}
		delete(committed, rel)
	}
	if len(committed) > 0 {
		left := make([]string, 0, len(committed))
		for name := range committed {
			left = append(left, outputDir+"/"+name)
		}
		sort.Strings(left)
		return fmt.Errorf("残留产物(IDL 已不含对应类型): %s,请运行 `go run ./cmd/gen-ts` 后删除", strings.Join(left, ", "))
	}
	return nil
}

func writeAll(files map[string]string) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("创建输出目录: %w", err)
	}
	names := make([]string, 0, len(files))
	for rel := range files {
		names = append(names, rel)
	}
	sort.Strings(names)
	for _, rel := range names {
		p := filepath.Join(outputDir, rel)
		if err := os.WriteFile(p, []byte(files[rel]), 0o644); err != nil {
			return fmt.Errorf("写出 %s: %w", p, err)
		}
	}
	return nil
}
