#!/usr/bin/env bash
#
# gen-model.sh — 从 idl/*.thrift 再生成纯模型类型到 gen/<domain>/
#
# 本仓是契约层单一真相源:IDL 定义与生成产物都在本仓内,
# 不再依赖旧单体仓库(此前需回 FileCodeBox/backend 跑 make gen 再手工拷贝)。
#
# 依赖: hz + thriftgo(版本需与既有产物一致,一键安装见 scripts/install-tools.sh)
# 产物: gen/<domain>/*.go(仅 model 纯类型,无 handler/router)
#
# 用法:
#   ./scripts/gen-model.sh            # 全量再生成
#   CHECK=1 ./scripts/gen-model.sh    # 只校验产物与仓内 gen/ 是否一致(CI 用)
set -euo pipefail
cd "$(dirname "$0")/.."

MODULE="github.com/filescodebox/contracts"
IDL_DIR="idl"
GEN_DIR="gen"
HZ_VERSION="v0.9.7"

fail() { echo -e "\033[1;31m[ERROR]\033[0m $1" >&2; exit 1; }

command -v hz       >/dev/null || fail "hz 未安装: go install github.com/cloudwego/hertz/cmd/hz@${HZ_VERSION}"
command -v thriftgo >/dev/null || fail "thriftgo 未安装: go install github.com/cloudwego/thriftgo/cmd/thriftgo@v0.4.3"

# 与旧单体 gen.sh 相同的过滤:仅处理带 service 定义的 IDL,
# 纯 struct/模板文件(api/error)不生成桩;其类型若被引用会随 include 自动带出。
IDLS=()
for f in "$IDL_DIR"/*.thrift "$IDL_DIR"/http/*.thrift; do
  [ -f "$f" ] || continue
  if grep -qE '^[[:space:]]*service[[:space:]]+[A-Za-z_][A-Za-z0-9_]*[[:space:]]*\{' "$f"; then
    IDLS+=("$f")
  else
    echo "跳过无 service 定义的 IDL: $f (纯 struct/文档)"
  fi
done
[ ${#IDLS[@]} -gt 0 ] || fail "未找到带 service 定义的 thrift IDL"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/model"
printf '// Code generated by hz. DO NOT EDIT.\n\nhz version: %s\nmodelDir: model\n' "$HZ_VERSION" > "$WORK/.hz"

echo "==> 共 ${#IDLS[@]} 个 IDL,开始再生成模型..."
for f in "${IDLS[@]}"; do
  echo "  - hz update: $f"
  hz update --idl "$f" --module "$MODULE" --out_dir "$WORK" --model_dir model -I "$IDL_DIR"
done

if [ "${CHECK:-0}" = "1" ]; then
  echo "==> 校验生成产物与 $GEN_DIR/ 是否一致..."
  if diff -r "$WORK/model" "$GEN_DIR" >/tmp/fcb-contracts-gen.diff 2>&1; then
    echo "✓ 一致,gen/ 与 idl/ 定义同步"
  else
    echo "✗ gen/ 与 idl/ 不同步,差异已写入 /tmp/fcb-contracts-gen.diff:" >&2
    head -30 /tmp/fcb-contracts-gen.diff >&2
    echo "请运行 ./scripts/gen-model.sh 更新后提交" >&2
    exit 1
  fi
  exit 0
fi

echo "==> 同步产物 $WORK/model → $GEN_DIR/"
rm -rf "$GEN_DIR"
mkdir -p "$GEN_DIR"
cp -R "$WORK/model/." "$GEN_DIR/"

echo "✓ 已再生成 gen/: $(ls "$GEN_DIR" | tr '\n' ' ')"
echo "  建议: git diff $GEN_DIR 检查后提交"
