#!/usr/bin/env bash
#
# install-tools.sh — 一键安装 IDL 模型生成工具链(hz + thriftgo)
#
# 版本与仓内 gen/ 产物的生成器保持一致(见各文件头部 "Code generated by" 注释),
# 升级工具版本后请 ./scripts/gen-model.sh 全量再生成并检查 diff。
#
# 用法:
#   ./scripts/install-tools.sh            # 安装全部
#   ./scripts/install-tools.sh hz         # 只装 hz
#   ./scripts/install-tools.sh thriftgo   # 只装 thriftgo
#
# 需要 GOPATH/bin 在 PATH 里(默认 ~/go/bin)

set -euo pipefail

GREEN='\033[0;32m'
NC='\033[0m'
log() { echo -e "${GREEN}[INFO]${NC}  $*"; }

# 与 gen/ 现有产物匹配的版本
HZ_VERSION="${HZ_VERSION:-v0.9.7}"
THRIFTGO_VERSION="${THRIFTGO_VERSION:-v0.4.3}"

install_hz() {
  log "安装 hz ${HZ_VERSION} (CloudWeGo Hertz 代码生成器)..."
  go install "github.com/cloudwego/hertz/cmd/hz@${HZ_VERSION}"
  log "hz 安装完成: $(command -v hz || echo '~/go/bin/hz')"
}

install_thriftgo() {
  log "安装 thriftgo ${THRIFTGO_VERSION} (thrift IDL 编译器)..."
  go install "github.com/cloudwego/thriftgo@${THRIFTGO_VERSION}"
  log "thriftgo 安装完成: $(command -v thriftgo || echo '~/go/bin/thriftgo')"
}

case "${1:-all}" in
  hz)       install_hz ;;
  thriftgo) install_thriftgo ;;
  all)      install_hz; install_thriftgo ;;
  *) echo "用法: $0 [hz|thriftgo|all]" >&2; exit 1 ;;
esac
